---
- hosts: all
  sudo: yes
  tasks:
   - name: Stop and disable firewalld.
     service:
       name: firewalld
       state: stopped
       enabled: False
   - name: disable selinux
     selinux:
       state: disabled
