---
- hosts: all
  sudo: yes
  tasks:
      - name: set hosts
        action: template src=../templates/hosts.j2 dest=/etc/hosts
      - name: Update /etc/sysconfig/network file
        when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
        action: lineinfile dest=/etc/sysconfig/network regexp=^HOSTNAME= line=HOSTNAME={{inventory_hostname}}
      - name: test 
        hostname:
         name: "{{ inventory_hostname }}"

